# Generated by Django 2.2.4 on 2019-08-18 13:20

import django.core.validators
from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emp_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Manegament'), ('3', 'Compensation'), ('4', 'Suggestions'), ('5', 'Complaint')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(whitelist=['ems']), django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(20), feedback.models.validate_allowed_domains]),
        ),
    ]
